### PR TITLE
Upgrade to uswds 2.0

### PR DESCRIPTION
**Pull request by hoaiandang**
When served, it raises the exception: "ERROR `/assets/css/main.css' not found." As a result, the page displays only images and links with no styling.

### CODE REVIEW

**Comment by afeld** [comment]
Note there are some differences—not sure how much we care.

Screen Shot 2020-07-28 at 5 54 03 PM

**Comment by adunkman** [comment]
Give me a shout when this is ready for review! Thanks for taking a look at this!

**Comment by afeld** [comment]
I think it's ready! Depends how much you care about those visual changes, I suppose.

FYI, @hoaiandang's error up top seemed to be a local caching issue.

**Comment by hoaiandang** [comment]
I can do the first pass! A couple of the other sites are running into similar issues, so I'm trying to figure those out. I'll let you know if I find anything or if I need any help.

**Comment by hoaiandang** [comment]
Additionally, the layout of the footer is different
Screen Shot 2020-08-02 at 9 32 27 PM

**Comment by hoaiandang** [comment]
Fixed the alert styling, the only big difference left is with the search bar.

Original:
Screen Shot 2020-08-04 at 9 48 08 PM

New:
Screen Shot 2020-08-04 at 9 48 03 PM

**Comment by hoaiandang** [comment]
Other than that, I think it's pretty much ready to ship! @adunkman

**Comment by hoaiandang** [comment]
Oh, thanks for catching that. Fixed!

**Comment by adunkman** [comment]
Looks like there are still some bullets hanging out where they shouldn’t be:

screenshot of accordion with bullets present

Looking at the USWDS v2 docs: 

- The wrapping element should be a `<div>` instead of a `<ul>`, and it should have two classes: `usa-accordion usa-accordion--bordered`
- Items should no longer be wrapped in a `<li>` element.
- The accordion button should be wrapped in an appropriate heading element (in this case, `<h4>`) with class `usa-accordion__heading`.

**Comment by hoaiandang** [comment]
Got it, thanks. Working on that now!

**Comment by hoaiandang** [comment]
Alright, how's that look?

**Comment by hoaiandang** [comment]
Of course! Glad to help

**Pull request merged**
