### PR TITLE
Fix grammatical error/typo in you/your

### PR DESCRIPTION
**Pull request by garrypolley**
There appeared to be a typo in the interview section with regards to a `you/your` mix-up.

### CODE REVIEW

**Comment by garrypolley** [comment]
Random assignment of reviewers. I have no idea how to put the PR on the radar, also not a big change.

**Comment by nkkl** [comment]
@garrypolley thanks for catching that!

@tbaxter-18f who stewards this now that Clint has shifted teams? Is it @adunkman? Either ways, change looks 👍 to me.

**Comment by adunkman** [comment]
It me! I should probably watch this repo. 😄 

Thanks @nkkl for the nudge, and @garrypolley for the PR!

**Comment by adunkman** [comment]
(Just a status update here, figuring out what’s up with CI and what permissions I need to merge this).

**Pull request merged**
